runtime: php55
threadsafe: yes
api_version: 1

handlers:
- url: /(.*\.(html|css|js))
  static_files: \1
  upload: .*\.(html|css|js)$
  application_readable: true

- url: .*
  script: index.php

skip_files:
- ^(.*/)?\.zip$
- ^(.*/)?\.bat$
- ^(.*/)?\.sh$
- ^(.*/)?\.md$
- ^vendor